export const vaccins = [
  {
    id: 'vaccin-1',
    nom: 'BBIBP-CorV',
    inventeurs: 'Sinopharm',
    lieuProduction: 'Chine',
    technologie: 'virus inactivé',
    quantite: 420,
    prixUnitaire: 17,
    approuve: 'oui',
    imageUrl: '../bbibp-corv.jpg',
  },
  {
    id: 'vaccin-2',
    nom: 'Sputnik V',
    inventeurs: 'Gamaleya',
    lieuProduction: ['Russie', 'Inde'],
    technologie: 'adenovirus',
    quantite: 130,
    prixUnitaire: 12,
    approuve: 'non',
    imageUrl: '../sputnik-v.jpg',
  },
  {
    id: 'vaccin-3',
    nom: 'AZD1222',
    inventeurs: 'AstraZeneca, University of Oxford',
    lieuProduction: ['Royaume-Uni', 'Brésil', 'Inde'],
    technologie: 'adenovirus',
    quantite: 5028,
    prixUnitaire: 1.78,
    approuve: 'non',
    imageUrl: '../azd1222.jpg',
  },
  {
    id: 'vaccin-4',
    nom: 'Tozinameran',
    inventeurs: ['BioNTech', 'Pfizer', 'Fosun Pharma'],
    lieuProduction: ['Allemagne', 'USA'],
    technologie: 'ARN messager',
    quantite: 980,
    prixUnitaire: 14,
    approuve: 'oui',
    imageUrl: '../tozinameran.jpg',
  },
  {
    id: 'vaccin-5',
    nom: 'mRNA-1273',
    inventeurs: ['Moderna', 'NIAID', 'BARDA'],
    lieuProduction: 'USA',
    technologie: 'ARN messager',
    quantite: 240,
    prixUnitaire: 28,
    approuve: 'non',
    imageUrl: '../mrna-1273.jpg',
  },
  {
    id: 'vaccin-6',
    nom: 'Ad26.COV2.S',
    inventeurs: ['Johnson & Johnson', 'BIDMC'],
    lieuProduction: ['USA', 'Amérique du Sud', 'Ukraine', 'Afrique du Sud'],
    technologie: 'adenovirus',
    quantite: 110,
    prixUnitaire: 31,
    approuve: 'non',
    imageUrl: '../ad26-cov2-s.jpg',
  },
];
